# Generated by Django 3.2.4 on 2021-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=280),
        ),
    ]
