# Generated by Django 3.2.4 on 2021-07-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210724_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='item',
            new_name='title',
        ),
    ]
