# Generated by Django 3.2.4 on 2021-07-26 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210726_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='createds', to=settings.AUTH_USER_MODEL),
        ),
    ]
