# Generated by Django 3.2.4 on 2021-07-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winner',
        ),
    ]
